### ISSUE TITLE
Using given example in new app

### ISSUE THREAD

**Issue by DMehro** [phnx47/Prometheus.Client#5]
HI, I am new to prometheus and stumbled upon your git repo .

I took downloaded source code and while running in my local box it is not working . Can you please spare some time to help me understand promoetheus -

a) If I am using prometheus in my application , Is it required to write client , does prometheus client wont suffice ?
b) How to use prometheus in web application , for example if I have three controllers in my project am I supposed to use prometheus logging specific code in each and every controller or what is best approach to use prometheus in .net MVC web api ?
c) Give sample does not work , when I start debugging it just hanged up and does not respond ?

**Comment by phnx47** [comment]
I recommend use https://github.com/phnx47/Prometheus.Client.Owin for Web Application. 
I will write special extensions for MVC/WebApi. Here: https://github.com/phnx47/Prometheus.Client.Owin.RequestDurations.
You should see the metrics in '/metrics' route by default.

**Comment by DMehro** [comment]
I tried out https://github.com/phnx47/Prometheus.Client.Owin  example , I could not run this application. Do you know if I have to tweak something to make it work and see data in prometheus server ?

**Comment by phnx47** [comment]
1) Run prometheus server. Don't  forget fill scrape_configs in prometheus.yml, example
```
# my global config
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
      - targets: ['localhost:9090']
      
  - job_name: 'testing'
    static_configs:
      - targets: ['localhost:5000']

```
2) Run WebCoreApplication in Prometheus.Client.Owin.
3) Open /api/counter for write test metric
4) Open /metrics. You should see your metrics
![image](https://user-images.githubusercontent.com/1101691/33277397-77c30018-d3a9-11e7-93b4-4ef8bfc4aa9c.png)

5) Go to Prometheus. By defautl: http://localhost:9090.
![image](https://user-images.githubusercontent.com/1101691/33277438-954b64c2-d3a9-11e7-8554-2cc25bf0e03e.png)
